// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WSCajaAhorros.Infrastructure.Persistence;

#nullable disable

namespace WSCajaAhorros.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251223072539_InitialwithSnake")]
    partial class InitialwithSnake
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("pk_permisos");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_permisos_codigo");

                    b.ToTable("permisos", (string)null);
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_codigo");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.RolPermiso", b =>
                {
                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("uuid")
                        .HasColumnName("permiso_id");

                    b.HasKey("RolId", "PermisoId")
                        .HasName("pk_roles_permisos");

                    b.HasIndex("PermisoId")
                        .HasDatabaseName("ix_roles_permisos_permiso_id");

                    b.ToTable("roles_permisos", (string)null);
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo_electronico");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean")
                        .HasColumnName("esta_activo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_contrasena");

                    b.Property<bool>("MfaHabilitado")
                        .HasColumnType("boolean")
                        .HasColumnName("mfa_habilitado");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("SaltContrasena")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("salt_contrasena");

                    b.Property<DateTime?>("UltimoInicioSesion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_inicio_sesion");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_correo_electronico");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_nombre_usuario");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.UsuarioAccesoHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer")
                        .HasColumnName("dia_semana");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval")
                        .HasColumnName("hora_inicio");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_usuarios_accesos_horarios");

                    b.HasIndex("UsuarioId", "DiaSemana", "HoraInicio", "HoraFin")
                        .HasDatabaseName("ix_usuarios_accesos_horarios_usuario_id_dia_semana_hora_inicio");

                    b.ToTable("usuarios_accesos_horarios", (string)null);
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.UsuarioRol", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("UsuarioId", "RolId")
                        .HasName("pk_usuarios_roles");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuarios_roles_rol_id");

                    b.ToTable("usuarios_roles", (string)null);
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.RolPermiso", b =>
                {
                    b.HasOne("WSCajaAhorros.Domain.Security.Permiso", "Permiso")
                        .WithMany("Roles")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roles_permisos_permisos_permiso_id");

                    b.HasOne("WSCajaAhorros.Domain.Security.Rol", "Rol")
                        .WithMany("Permisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_permisos_roles_rol_id");

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.UsuarioAccesoHorario", b =>
                {
                    b.HasOne("WSCajaAhorros.Domain.Security.Usuario", "Usuario")
                        .WithMany("AccesosHorarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_accesos_horarios_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.UsuarioRol", b =>
                {
                    b.HasOne("WSCajaAhorros.Domain.Security.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_roles_roles_rol_id");

                    b.HasOne("WSCajaAhorros.Domain.Security.Usuario", "Usuario")
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_roles_usuarios_usuario_id");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.Permiso", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.Rol", b =>
                {
                    b.Navigation("Permisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.Usuario", b =>
                {
                    b.Navigation("AccesosHorarios");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
