// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WSCajaAhorros.Infrastructure.Persistence;

#nullable disable

namespace WSCajaAhorros.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251220065641_AgregarSociosyCuentas")]
    partial class AgregarSociosyCuentas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WSCajaAhorros.Domain.Cuentas.Cuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductoCuentaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SocioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("permisos", (string)null);
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.RolPermiso", b =>
                {
                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("uuid");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("roles_permisos", (string)null);
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("MfaHabilitado")
                        .HasColumnType("boolean");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SaltContrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoInicioSesion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.UsuarioAccesoHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "DiaSemana", "HoraInicio", "HoraFin");

                    b.ToTable("usuarios_accesos_horarios", (string)null);
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.UsuarioRol", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("usuarios_roles", (string)null);
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Socios.CorreoSocio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Etiqueta")
                        .HasColumnType("text");

                    b.Property<Guid>("SocioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("CorreoSocio");
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Socios.DireccionSocio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("boolean");

                    b.Property<string>("Etiqueta")
                        .HasColumnType("text");

                    b.Property<Guid>("SocioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("DireccionSocio");
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Socios.Socio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellidos")
                        .HasColumnType("text");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaConstitucion")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("NombreComercial")
                        .HasColumnType("text");

                    b.Property<string>("Nombres")
                        .HasColumnType("text");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("text");

                    b.Property<int>("TipoPersona")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Socios");
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Socios.TelefonoSocio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Etiqueta")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SocioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("TelefonoSocio");
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Cuentas.Cuenta", b =>
                {
                    b.OwnsOne("WSCajaAhorros.Domain.Common.Dinero", "Saldo", b1 =>
                        {
                            b1.Property<Guid>("CuentaId")
                                .HasColumnType("uuid");

                            b1.HasKey("CuentaId");

                            b1.ToTable("Cuentas");

                            b1.WithOwner()
                                .HasForeignKey("CuentaId");
                        });

                    b.Navigation("Saldo")
                        .IsRequired();
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.RolPermiso", b =>
                {
                    b.HasOne("WSCajaAhorros.Domain.Security.Permiso", "Permiso")
                        .WithMany("Roles")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WSCajaAhorros.Domain.Security.Rol", "Rol")
                        .WithMany("Permisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.UsuarioAccesoHorario", b =>
                {
                    b.HasOne("WSCajaAhorros.Domain.Security.Usuario", "Usuario")
                        .WithMany("AccesosHorarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.UsuarioRol", b =>
                {
                    b.HasOne("WSCajaAhorros.Domain.Security.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WSCajaAhorros.Domain.Security.Usuario", "Usuario")
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Socios.CorreoSocio", b =>
                {
                    b.HasOne("WSCajaAhorros.Domain.Socios.Socio", null)
                        .WithMany("Correos")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Socios.DireccionSocio", b =>
                {
                    b.HasOne("WSCajaAhorros.Domain.Socios.Socio", null)
                        .WithMany("Direcciones")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WSCajaAhorros.Domain.Common.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("DireccionSocioId")
                                .HasColumnType("uuid");

                            b1.HasKey("DireccionSocioId");

                            b1.ToTable("DireccionSocio");

                            b1.WithOwner()
                                .HasForeignKey("DireccionSocioId");
                        });

                    b.Navigation("Direccion")
                        .IsRequired();
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Socios.Socio", b =>
                {
                    b.OwnsOne("WSCajaAhorros.Domain.Socios.Identificacion", "Identificacion", b1 =>
                        {
                            b1.Property<Guid>("SocioId")
                                .HasColumnType("uuid");

                            b1.HasKey("SocioId");

                            b1.ToTable("Socios");

                            b1.WithOwner()
                                .HasForeignKey("SocioId");
                        });

                    b.Navigation("Identificacion")
                        .IsRequired();
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Socios.TelefonoSocio", b =>
                {
                    b.HasOne("WSCajaAhorros.Domain.Socios.Socio", null)
                        .WithMany("Telefonos")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.Permiso", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.Rol", b =>
                {
                    b.Navigation("Permisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Security.Usuario", b =>
                {
                    b.Navigation("AccesosHorarios");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("WSCajaAhorros.Domain.Socios.Socio", b =>
                {
                    b.Navigation("Correos");

                    b.Navigation("Direcciones");

                    b.Navigation("Telefonos");
                });
#pragma warning restore 612, 618
        }
    }
}
